name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | sed -e 's/\r$//' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no root@217.26.30.27 "echo 'SSH работает!'"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh root@217.26.30.27 << 'EOF'
            cd /root/osushenie_bot/SVVR_Osushenie_bot || exit
            git pull --ff-only origin main || exit
            .venv/bin/pip install -r requirements.txt || exit
            systemctl restart svvr-osushenie-bot.service
            systemctl is-active --quiet svvr-osushenie-bot.service
          EOF
